PATHS:
    Project_path: './'
    data_path: 'data/'
    model_path: 'models/'

model_name_random_forest : rf.pkl
base_model_name_lr : lr.pkl
parameter_grid_rf:
    param_grid : {
    'bootstrap': [True], # Consider bootstapping
    'max_features': [2, 3, 4, 5, 6], # number of features to consider at every split
    'n_estimators': [100, 200, 500], # Number of trees in random forest
    'criterion': ['gini'], # Measure of quality of split. Gini impurity is used as a measure for split .Gini impurity is a measure of how often a randomly chosen element from the set would be incorrectly labeled if it was randomly labeled according to the distribution of labels in the subset.
    'max_depth': [10, 20, 30, 40, 50, 60, 70, 80], # Maximum number of levels in tree
    'min_samples_split': [2, 5, 10], # Minimum number of samples required to split a node
    'min_samples_leaf': [1, 2, 4], # Minimum number of samples required at each leaf node
    'random_state': [2022] # Random state
    }
cat_cols:
  [
    "car_feature_1",
    "car_feature_2",
    "car_feature_3",
    "car_feature_4",
    "car_feature_5",
    "car_feature_6",
    "car_feature_7",
    "car_feature_8",
    "car_feature_9",
    "car_feature_10",
    "car_feature_11",
    "query_feature_1",
    "query_feature_2",
    "query_feature_3",
    "duration",
    "target",
  ]

continous_cols:
  [
    "price",
    "cont_car_feature_1",
    "cont_car_feature_2",
    "cont_car_feature_3",
    "cont_car_feature_4",
  ]

categorify_cols:
  [
    "car_feature_1",
    "car_feature_2",
    "car_feature_3",
    "car_feature_4",
    "car_feature_5",
    "car_feature_6",
    "car_feature_7",
    "car_feature_8",
    "car_feature_9",
    "car_feature_10",
    "car_feature_11",
    "query_feature_1",
    "query_feature_2",
    "query_feature_3",
    "duration",
    "ts_weekday",
    "ts_day",
    "ts_month",
  ]

count_encoded_cols:
  [
    "car_feature_1_Categorify",
    "car_feature_2_Categorify",
    "car_feature_3_Categorify",
    "car_feature_4_Categorify",
    "car_feature_5_Categorify",
    "car_feature_6_Categorify",
    "car_feature_7_Categorify",
    "car_feature_8_Categorify",
    "car_feature_9_Categorify",
    "car_feature_10_Categorify",
    "car_feature_11_Categorify",
    "query_feature_1_Categorify",
    "query_feature_2_Categorify",
    "query_feature_3_Categorify",
    "duration_Categorify",
    "ts_weekday_Categorify",
    "ts_day_Categorify",
    "ts_month_Categorify",
  ]

date_cols: ["query_date", "pickup_date"]

required_cols:
  [
    "query_id",
    "veh_id",
    "query_date",
    "car_feature_1",
    "car_feature_2",
    "price",
    "car_feature_3",
    "car_feature_4",
    "car_feature_5",
    "cont_car_feature_1",
    "cont_car_feature_2",
    "cont_car_feature_3",
    "car_feature_6",
    "car_feature_7",
    "car_feature_8",
    "cont_car_feature_4",
    "car_feature_9",
    "car_feature_10",
    "car_feature_11",
    "query_feature_1",
    "query_feature_2",
    "duration",
    "pickup_date",
    "query_feature_3",
    "target",
  ]

cat_cols_for_feature_selection:
  [
    "car_feature_1",
    "car_feature_2",
    "car_feature_3",
    "car_feature_4",
    "car_feature_5",
    "car_feature_6",
    "car_feature_7",
    "car_feature_8",
    "car_feature_9",
    "car_feature_10",
    "car_feature_11",
    "query_feature_1",
    "query_feature_2",
    "query_feature_3",
    "duration",
    "ts_weekday",
    "ts_day",
    "ts_month",
    "car_feature_1_Categorify",
    "car_feature_2_Categorify",
    "car_feature_3_Categorify",
    "car_feature_4_Categorify",
    "car_feature_5_Categorify",
    "car_feature_6_Categorify",
    "car_feature_7_Categorify",
    "car_feature_8_Categorify",
    "car_feature_9_Categorify",
    "car_feature_10_Categorify",
    "car_feature_11_Categorify",
    "query_feature_1_Categorify",
    "query_feature_2_Categorify",
    "query_feature_3_Categorify",
    "duration_Categorify",
    "ts_weekday_Categorify",
    "ts_day_Categorify",
    "ts_month_Categorify",
  ]

cont_cols_for_feature_selection:
  [
    "price",
    "cont_car_feature_1",
    "cont_car_feature_2",
    "cont_car_feature_3",
    "cont_car_feature_4",
    "CE_car_feature_1_Categorify",
    "CE_car_feature_2_Categorify",
    "CE_car_feature_3_Categorify",
    "CE_car_feature_4_Categorify",
    "CE_car_feature_5_Categorify",
    "CE_car_feature_6_Categorify",
    "CE_car_feature_7_Categorify",
    "CE_car_feature_8_Categorify",
    "CE_car_feature_9_Categorify",
    "CE_car_feature_10_Categorify",
    "CE_car_feature_11_Categorify",
    "CE_query_feature_1_Categorify",
    "CE_query_feature_2_Categorify",
    "CE_query_feature_3_Categorify",
    "CE_duration_Categorify",
    "CE_ts_weekday_Categorify",
    "CE_ts_day_Categorify",
    "CE_ts_month_Categorify",
    "time_to_pickup",
  ]

all_features:
  [
    "car_feature_1",
    "car_feature_2",
    "car_feature_3",
    "car_feature_4",
    "car_feature_5",
    "car_feature_6",
    "car_feature_7",
    "car_feature_8",
    "car_feature_9",
    "car_feature_10",
    "car_feature_11",
    "query_feature_1",
    "query_feature_2",
    "query_feature_3",
    "duration",
    "ts_weekday",
    "ts_day",
    "ts_month",
    "car_feature_1_Categorify",
    "car_feature_2_Categorify",
    "car_feature_3_Categorify",
    "car_feature_4_Categorify",
    "car_feature_5_Categorify",
    "car_feature_6_Categorify",
    "car_feature_7_Categorify",
    "car_feature_8_Categorify",
    "car_feature_9_Categorify",
    "car_feature_10_Categorify",
    "car_feature_11_Categorify",
    "query_feature_1_Categorify",
    "query_feature_2_Categorify",
    "query_feature_3_Categorify",
    "duration_Categorify",
    "ts_weekday_Categorify",
    "ts_day_Categorify",
    "ts_month_Categorify",
    "price",
    "cont_car_feature_1",
    "cont_car_feature_2",
    "cont_car_feature_3",
    "cont_car_feature_4",
    "CE_car_feature_1_Categorify",
    "CE_car_feature_2_Categorify",
    "CE_car_feature_3_Categorify",
    "CE_car_feature_4_Categorify",
    "CE_car_feature_5_Categorify",
    "CE_car_feature_6_Categorify",
    "CE_car_feature_7_Categorify",
    "CE_car_feature_8_Categorify",
    "CE_car_feature_9_Categorify",
    "CE_car_feature_10_Categorify",
    "CE_car_feature_11_Categorify",
    "CE_query_feature_1_Categorify",
    "CE_query_feature_2_Categorify",
    "CE_query_feature_3_Categorify",
    "CE_duration_Categorify",
    "CE_ts_weekday_Categorify",
    "CE_ts_day_Categorify",
    "CE_ts_month_Categorify",
    "time_to_pickup",
  ]
