cat_cols:
  [
    "car_feature_1",
    "car_feature_2",
    "car_feature_3",
    "car_feature_4",
    "car_feature_5",
    "car_feature_6",
    "car_feature_7",
    "car_feature_8",
    "car_feature_9",
    "car_feature_10",
    "car_feature_11",
    "query_feature_1",
    "query_feature_2",
    "query_feature_3",
    "duration",
    "target",
  ]

continous_cols:
  [
    "price",
    "cont_car_feature_1",
    "cont_car_feature_2",
    "cont_car_feature_3",
    "cont_car_feature_4",
  ]

categorify_columns:
  [
    "car_feature_1",
    "car_feature_2",
    "car_feature_3",
    "car_feature_4",
    "car_feature_5",
    "car_feature_6",
    "car_feature_7",
    "car_feature_8",
    "car_feature_9",
    "car_feature_10",
    "car_feature_11",
    "query_feature_1",
    "query_feature_2",
    "query_feature_3",
    "duration"]

date_columns:
  [
    "query_date",
    "pickup_date"
  ]